logsBucket: "gs://prod_fake_news_logs"
steps:
  - name: 'hashicorp/terraform:1.5.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
    dir: 'ias'
timeout: 1200s
