FROM apache/airflow:2.6.0-python3.10
# Set the Airflow home directory
ENV AIRFLOW_HOME=/opt/airflow
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY deploy/requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /requirements.txt

# Copy DAG files
COPY dags/ /opt/airflow/dags/
COPY plugins/ /opt/airflow/plugins/
USER root
# Init script if needed
COPY deploy/script/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER airflow
ENTRYPOINT ["/entrypoint.sh"]



# Initialize the Airflow database before starting the webserver
#CMD ["bash", "-c", "airflow db init && airflow webserver --port 8080"]